"""add user profile fields

Revision ID: 56021e42831d
Revises: 839c648bcbb2
Create Date: 2026-03-25 23:00:47.227143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56021e42831d'
down_revision = '839c648bcbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('weight_kg')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
